#!/bin/bash
trap qemu_restore err SIGINT exit

function qemu_restore() {
mv /usr/bin/qemu-system-x86_64.ori /usr/bin/qemu-system-x86_64
}

mv /usr/bin/qemu-system-x86_64 /usr/bin/qemu-system-x86_64.ori
cp /opt/qemu/bin/qemu-system-x86_64 /usr/bin/qemu-system-x86_64 

guestfish $@ 
